# Generated by Django 3.2.13 on 2022-07-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
