# Generated by Django 3.2.13 on 2022-07-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_cursos_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='descripcion',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='subtitulo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
