# Generated by Django 3.2.13 on 2022-07-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_auto_20220720_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='camada',
            new_name='autor',
        ),
    ]
