# Generated by Django 3.2.13 on 2022-07-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_rename_camada_cursos_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='nombre',
            new_name='video',
        ),
    ]
