# Generated by Django 3.2.13 on 2022-07-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_rename_nombre_cursos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='fecha',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
