# Generated by Django 3.2.13 on 2022-07-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_contacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Consultas',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
