# Generated by Django 3.2.13 on 2022-07-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_auto_20220719_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultas',
        ),
    ]
