# Generated by Django 3.2.13 on 2022-07-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_delete_consultas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('email_usuario', models.CharField(max_length=30)),
                ('detalle_usuario', models.CharField(max_length=30)),
            ],
        ),
    ]
