# Generated by Django 3.2.13 on 2022-07-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_alter_consultas_email_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultas',
            old_name='detalle_usuario',
            new_name='detalle',
        ),
        migrations.RenameField(
            model_name='consultas',
            old_name='email_usuario',
            new_name='email',
        ),
    ]
