# Generated by Django 3.2.13 on 2022-07-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_auto_20220719_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='detalle',
            field=models.CharField(max_length=100),
        ),
    ]
