# Generated by Django 3.2.13 on 2022-07-19 22:47

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0012_alter_consultas_detalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='camada',
            new_name='encabezado',
        ),
        migrations.AddField(
            model_name='cursos',
            name='descripcion',
            field=models.CharField(default=builtins.id, max_length=400),
            preserve_default=False,
        ),
    ]
