# Generated by Django 3.2.13 on 2022-07-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0013_auto_20220719_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='encabezado',
            new_name='camada',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='descripcion',
        ),
    ]
