# Generated by Django 3.2.13 on 2022-07-19 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0015_noticias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticias',
        ),
    ]
