# Generated by Django 3.2.13 on 2022-07-19 22:54

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0016_delete_noticias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='camada',
            new_name='encabezado',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='cursos',
            name='detalle',
            field=models.CharField(default=builtins.id, max_length=100),
            preserve_default=False,
        ),
    ]
