# Generated by Django 3.2.13 on 2022-07-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0018_auto_20220719_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='fechac',
            field=models.DateField(max_length=255, null=True),
        ),
    ]
