# Generated by Django 3.2.13 on 2022-07-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0019_consultas_fechac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='camada',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cursos',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='encabezado',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='fechac',
            field=models.DateField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='titulo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
