# Generated by Django 3.2.13 on 2022-07-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0020_auto_20220719_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultas',
            name='fechac',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='encabezado',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='fechac',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='titulo',
        ),
        migrations.AddField(
            model_name='cursos',
            name='camada',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
