# Generated by Django 3.2.13 on 2022-07-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0021_auto_20220719_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='camada',
            new_name='encabezado',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='cursos',
            name='descripcion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='fechac',
            field=models.DateField(max_length=30, null=True),
        ),
    ]
