# Generated by Django 3.2.13 on 2022-07-20 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0023_auto_20220719_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
