# Generated by Django 3.2.13 on 2022-07-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0024_auto_20220720_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultas',
            name='detalle',
            field=models.CharField(max_length=500),
        ),
    ]
