# Generated by Django 3.2.13 on 2022-07-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0025_alter_consultas_detalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='camada',
            new_name='video',
        ),
    ]
