# Generated by Django 3.2.13 on 2022-07-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0027_alter_cursos_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='video',
        ),
        migrations.AddField(
            model_name='cursos',
            name='camada',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
